#!/bin/sh

set -eu

cd "$(dirname "$0")"

alias docker_sync="rsync -e 'docker exec -i' --blocking-io"

mkdir -p output

docker_sync \
  -avr --delete \
  "$(./builder name):/home/user/output/" \
  output
